eureka:
  instance:
    prefer-ip-address: true

spring:  
  cloud:
    loadbalancer:
      retry:
        enabled: false

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false

# hystrix:
#   threadpool:
#     default:
#       coreSize: 1000
#       maximumSize: 1000 
#       maxQueueSize: 1000
#   command:
#     default:
#       execution:
#         timeout:
#           enabled: true      
#         isolation:
#           strategy: THREAD
#           thread:
#             timeoutInMilliseconds: 3000  